### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by Tlntin** [tmplink/tmplink_cli#1]
使用该工具上传一个14G大小的文件时候，提示413。
但是用浏览器点击上传，则一切正常。

**Comment by tmplink** [comment]
CLI 上传目前最大支持 10GB。
关于此问题的具体情况，请参考此[链接](https://bbs.tmp.link/d/27-cli-%E4%B8%8A%E4%BC%A0%E6%94%AF%E6%8C%81-50gb-%E5%A4%A7%E6%96%87%E4%BB%B6%E7%9A%84%E8%AE%A1%E5%88%92)。
