### ISSUE TITLE
希望上传时能滚动日志或者是显示进度

### ISSUE THREAD

**Issue by wsndshx** [tmplink/tmplink_cli#4]
希望上传时能滚动日志或者是显示进度，这样在上传大文件时能知道程序目前的上传状态。而不是只有

```
正在上传 [文件名]
```

这样的输出

**Comment by wsndshx** [comment]
对代码修改了一下，将71行修改为如下的内容

```shell
        echo `curl -# -k -F "file=@\"$selected_file\"" -F "token=$token" -F "model=$model" -F "mrid=$mrid" -X POST "https://tmp-cli.vx-cdn.com/app/upload_cli"`
```

即可显示出上传进度条

![image](https://github.com/tmplink/tmplink_cli/assets/7829265/2e676267-74b7-411b-b69d-72d3113b233d)

**Comment by tmplink** [comment]
CURL 由于在多个系统上都可用，因此需要在 Windows 和 MacOS 上都完成兼容性测试后，此命令方可发布。
